### ISSUE TITLE
ImageMagick binary not found in docker container

### ISSUE THREAD

**Issue by CarlitosDroid** [alexanderscott/iconerator#13]
I'm running a nodejs docker container:

`docker run -it --rm -v $(pwd):/home node:10 bash`

I have installed `npm install -g iconerator`

However after running iconerator icon.png I got:

`ImageMagick binary not found`

**Comment by georgemck** [comment]
Error is generated by cli.js for "iconerator.checkDependencies". Try commenting out "process.exit(1);" which ends the program. 

=====

I installed iconerator under Microsoft Windows WSL (Windows Subsystem Linux). I had error "ImageMagick binary not found" I also installed this program for Mac OS Mojave which did not produce this error. The check dependency function relies on /urs/bin/type function which was not available on my Linux distro.

**Comment by alexanderscott** [comment]
Thanks @georgemck and @CarlitosDroid .  Pushed a quick fix in https://github.com/alexanderscott/iconerator/pull/14 which will not exit the program if `checkDependencies` fails.  If you have a suggestion for how to properly check dependencies across linux versions please lmk.
