### ISSUE TITLE
ImageMagick binary not found

### ISSUE THREAD

**Issue by olivinesguerra** [alexanderscott/iconerator#27]
When building the app. It doesn't return any error. But when I try running iconerator. Returns a ImageMagick binary not found error.

Thanks

My Dockerfile:

FROM dwchiang/nginx-php-fpm:latest

WORKDIR /var/www/html

COPY . .

ARG  DEBIAN_FRONTEND="noninteractive"

ENV NODE_VERSION 18.15.0
ENV NVM_DIR /usr/local/nvm

ENV APP_ENV=staging
ENV APP_DEBUG=false
ENV COMPOSER_ALLOW_SUPERUSER=1

RUN mkdir -p $NVM_DIR

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    mariadb-client \
    libpng-dev \
    autoconf \
    libzip-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    ffmpeg \
    imagemagick \
    libmagickwand-dev --no-install-recommends \
    graphicsmagick 

# RUN pecl install imagick 
# RUN docker-php-ext-enable imagick
RUN apt-get install -y supervisor

RUN docker-php-ext-configure gd

RUN docker-php-ext-install  gd pdo_mysql mysqli opcache zip bcmath

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_MEMORY_LIMIT=-1 
RUN composer global require laravel/installer
RUN composer dump-autoload --optimize
RUN composer install --ignore-platform-reqs --no-dev --optimize-autoloader --apcu-autoloader --no-scripts

RUN curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

RUN . $NVM_DIR/nvm.sh \
    && nvm use $NODE_VERSION \
    && npm install iconerator -g \
    && npm install gm -g \
    && npm install imagemagick -g \
    && npm install aws-sdk -g

ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN chown -R www-data:www-data /var/www/html
RUN chmod 755 -R /var/www/html/storage/
RUN chmod 755 -R /var/www/html/export/
RUN chmod 755 -R /var/www/html/bootstrap/
RUN chmod 755 -R /var/www/html/input_source_path/

COPY ./deployment/staging/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

**Comment by olivinesguerra** [comment]
Found out that there is no /usr/bin/type exist. any idea to fix? @alexanderscott

**Comment by alexanderscott** [comment]
@olivinesguerra I believe https://github.com/alexanderscott/iconerator/pull/28 should fix your issue, as it replaces the check for /usr/bin/type. Thanks and lmk.
