### ISSUE TITLE
Not being able to make it work on ubuntu 16.04

### ISSUE THREAD

**Issue by lohanidamodar** [alexanderscott/iconerator#7]
I have installed imagemagick package but it still gives error ImageMagick bin not found

**Comment by alexanderscott** [comment]
@lohanidamodar sounds like it the binary may have not been linked or isn't in the node/npm include path.  you installed through the source code or `imagemagick` package via apt-get?

what are the outputs of the following from a bash term?
```shell
which magick
npm install gm
```

**Comment by lohanidamodar** [comment]
thanks! installing via npm worked!
