### ISSUE TITLE
Favicon could be single container file for web use.

### ISSUE THREAD

**Issue by johnelliott** [alexanderscott/iconerator#8]
Hey, I have a similar piece of code to incinerator over here: https://github.com/johnelliott/mobile-web-icon-helpers/blob/master/index.js, but I was going to use iconerator because I could avoid having npm-ify my repo.

I tried iconerator—worked great—but since I'm going for the apple-touch-icon naming convention it will just be easier to use the code I already have.

Issue:

In my research some time ago I found that favicon.ico is a container format for multiple images, so a 16px, 32px, 64px image can all be in one favicon.ico file: https://en.wikipedia.org/wiki/Favicon#HTML5_recommendation_for_icons_in_multiple_sizes

convert supports this, and I think I am doing it here:
```javascript
// make favicon.ico
  spawn('convert', [
    source,
    '-alpha',
    'off',
    '-resize',
    '32x32',
    '-define',
    'icon:auto-resize=32,16',
    'favicon.ico'
  ])
```

I am not sure how it'd work into config.json, but it's a thought for platforms that just hit domain/favicon.ico

nice work 👍 iconerator pulls together a lot of work and docs

**Comment by alexanderscott** [comment]
thanks for sharing @johnelliott

I did not know about the multiple, space-separated sizes allowed by HTML5 in a `favicon.ico`.  I'm going to leave the icon generation as-is, however, and leave it up to the user to decide whether or not to use a single favicon for the aforementioned multiple-use purpose.

That being said, it's a cool idea to auto-generate the HTML tags used for favicon and apple-touch-icons, as you do in your script.  Will consider adding this to iconerator's output next release.
